trigger:
- main

pool:
  vmImage: 'windows-latest' # Use a Windows agent for .NET development

variables:
  buildConfiguration: 'Release'
  # Azure App Service details for your backend API
  azureServiceConnection: 'thamco-api-b1851021-publish-profile' # Use the exact name of your new service connection
  webAppName: 'thamco-api-b1851021' # Your Backend API App Service name
  vmImageName: 'windows-latest'
  dotNetSdkVersion: '8.x'
  projectPath: 'src/ThAmCo.WebApi/ThAmCo.WebApi.csproj'
  databaseServer: 'thamcosy.database.windows.net'
  databaseName: 'thamcosystem'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotNetSdkVersion)'
  inputs:
    version: '$(dotNetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(projectPath)'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/publish'
    deploymentMethod: 'auto' 