trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/**

variables:
- group: StaticWebAppSecrets   # Link to the variable group containing AZURE_STATIC_WEB_APPS_API_TOKEN

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Use Node.js 20.x
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Install dependencies and build Vite app
- script: |
    cd frontend
    npm ci
    npm run build
  displayName: 'Install dependencies and build app'

# Step 3: Deploy to Azure Static Web Apps
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'frontend'            # Folder where your app source code is
    output_location: 'dist'             # Folder where the built files are output by Vite
    skip_app_build: true                # Skip automatic build step (already done)
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
  displayName: 'Deploy to Azure Static Web App'
