trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/**

variables:
- group: StaticWebAppSecrets   # Contains AZURE_STATIC_WEB_APPS_API_TOKEN

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Use Node.js 20.x
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Install dependencies and build Vite app
- script: |
    cd frontend
    npm ci
    npm run build
  displayName: 'Install dependencies and build app'

# Step 3: Copy staticwebapp.config.json to dist folder to ensure correct MIME types
- script: |
    cp frontend/staticwebapp.config.json frontend/dist/
  displayName: 'Copy staticwebapp.config.json to dist folder'

# Step 4: Deploy to Azure Static Web Apps
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'frontend'           # Source folder
    output_location: 'dist'            # Vite build output folder
    skip_app_build: true               # We already ran build step
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
  displayName: 'Deploy to Azure Static Web App'
