trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/**

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: StaticWebAppSecrets

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'npm install and build'
"scripts": {
  "build": "vite build"
}
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'frontend'
    output_location: 'dist'
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
