trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/**

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'frontend'
    output_location: 'dist'
    skip_app_build: false
    app_build_command: 'npm install && npm run build'
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
