trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/**

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'    # Match Node version to dependencies
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'frontend'
    output_location: 'dist'   # This must be the folder your build outputs inside 'frontend'
    skip_app_build: true      # Skip build because already built in previous step
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
